### ISSUE TITLE
Links don't work

### ISSUE THREAD

**Issue by stereobooster** [jaredpalmer/reason-react-native-web-example#4]
When I click links URL is changing in the browser address bar, but the component on the screen stays the same.

**Comment by kgoggin** [comment]
@stereobooster I think I also ran into this when I tried out the example and discovered it had something to do with the way react-router was not getting at the context correctly, perhaps? In any case, I'm nearly certain the issue lies with react-router integration, not razzle. I think there may be some other good examples out there of correct RR usage w/ Reason if that's what you're shooting for.

It'd probably be a good idea to update this example to use the official [ReasonReact router](https://reasonml.github.io/reason-react/docs/en/router.html), now that it exists, as that's a more official approach and is more in line with what this example is supposed to be showing (integration with RNW/Reason/Razzle). @jaredpalmer any objects to that?

**Comment by jaredpalmer** [comment]
@stereobooster go right ahead. Would love the update!

**Comment by kgoggin** [comment]
@stereobooster sorry, was on vacation last week. You're right - there's no official support for SSR, but it's not all that hard to do. The way I've got it set up in my app is to make my main `<App/>` component accept a `route` prop. Then wrote a method that mimics the string -> route matching logic from the official router module (it's a straight copy/paste) and use that on the server to figure out the route based on `req.path`, and pass it to my `<App/>`. I'm a little busy catching up this week but if I find some time I'll try to make the needed changes here!
